### ISSUE TITLE
Wesocket return 1005 error

### ISSUE THREAD

**Issue by AlenToma** [halilb/react-native-chess#4]
The `Websocket` is returning `1005` for some reason on android and web.

Now I am trying to look at the API and saw section [board](https://lichess.org/api#tag/Board). But as the URLs are not `websocket` I am unable to make the connection stay open. 

If you have time to look for this, and help understanding how this work it will really be great.

**Comment by halilb** [comment]
Hi @AlenToma,

Some stuff have probably changed on the Lichess API side since it's been too long. You'd probably need to reverse engineer the Lichess API traffic of the official Lichess app, and apply the same flow here. That's what I had done 4 years ago anyway.

I'm afraid I don't have any free time to investigate the problem. PRs are welcomed if you happen to fix it though.

**Comment by mmatheusmmiguel** [comment]
Hello,

Has anyone tested it on iOS?

**Comment by joy-mollick** [comment]
> Hi @AlenToma,
> 
> Some stuff have probably changed on the Lichess API side since it's been too long. You'd probably need to reverse engineer the Lichess API traffic of the official Lichess app, and apply the same flow here. That's what I had done 4 years ago anyway.
> 
> I'm afraid I don't have any free time to investigate the problem. PRs are welcomed if you happen to fix it though.

Brother , You have done a fantastic job .But now plz make free time to update codes to make it again work . I need a chess project urgently ,I became happy to see it .But after running it , I suddenly felt sad ,may be API documentation has been changed there ,hope to see you make it again work . Thanq you

**Comment by halilb** [comment]
> Brother , You have done a fantastic job .But now plz make free time to update codes to make it again work . I need a chess project urgently ,I became happy to see it .But after running it , I suddenly felt sad ,may be API documentation has been changed there ,hope to see you make it again work . Thanq you

This project is so old and there were no APIs when I built it. So the job is migrating all the websocket stuff to Lichess API, which is basically almost rewriting most of the project.

And I'm afraid I still don't have any free time to invest in this project. I guess it's a good idea to archive the project since it's no longer working.
